#ifndef MapService_idl
#define MapService_idl

#include "BasicDataType.idl"
#include "ExtendedDataTypes.idl"
#include "InterfaceDataTypes.idl"

module Map
{
    interface SimpleMap
    {
        void getMap(out string arg);
    };
};

#endif
